# -*- coding: utf-8 -*-
"""heart disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e40R6csetxX5Rf3dHTwbztVW03vZ3EOf
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("dataset/heart.csv")

print("Dataset Shape:", df.shape)
print(df.head())

imputer = SimpleImputer(strategy="most_frequent")
df = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

label_encoders = {}

for column in df.columns:
    if df[column].dtype == object:
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])
        label_encoders[column] = le

target = df.columns[-1]

X = df.drop(target, axis=1)
y = df[target]

target = df.columns[-1]

X = df.drop(target, axis=1)
y = df[target]

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

joblib.dump(model, "heart_model.pkl")

print("\nModel saved as heart_model.pkl")

sample = X.iloc[0:1]
prediction = model.predict(sample)

print("\nSample Prediction:", prediction[0])

if prediction[0] == 1:
    print("Heart Disease Detected")
else:
    print("No Heart Disease")